---

    name: >-
      âŒ
      [DO NOT CLICK]
      Reusable Zizmor
      
    
    on:
      workflow_call:
    
    env:
      FORCE_COLOR: 1  # Request colored output from CLI tools supporting it
      PIP_DISABLE_PIP_VERSION_CHECK: 1  # Hide "there's a newer pip" message
      PIP_NO_PYTHON_VERSION_WARNING: 1  # Hide "this Python is deprecated" message
      PIP_NO_WARN_SCRIPT_LOCATION: 1  # Hide "script dir is not in $PATH" message
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
    
    jobs:
      zizmor:
        name: ðŸ” Analyze repo with zizmor 
    
        runs-on: ubuntu-latest
    
        timeout-minutes: 3  # Account for network I/O
    
        steps:
        - name: Get the current repository from GitHub
          uses: actions/checkout@v4
          with:
            persist-credentials: false
    
        - name: Install the latest version of uv
          # yamllint disable-line rule:line-length
          uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86  # v5.4.2
    
        - name: Analyze GitHub Actions and workflow definitions with zizmor ðŸŒˆ
          run: uvx zizmor --format=sarif . > results.sarif
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Upload SARIF report into the GitHub repo code scanning
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: results.sarif
            category: zizmor
    
    ...